// Auto-generated by scripts/generate-types.ts. Do not edit.

// ─── Auto-generated operation query param types ───

export type ArtifactAddQuery = {
  name: string;
  fileName: string;
  fileMIMEType?: string;
  annotations?: Array<string>;
  artifactMIMEType?: string;
  append?: boolean;
  replace?: boolean;
};

export type ArtifactExtractQuery = {
  title?: string;
  digest?: string;
  excludeTitle?: boolean;
};

export type ArtifactLocalQuery = {
  name: string;
  path: string;
  fileName: string;
  fileMIMEType?: string;
  annotations?: Array<string>;
  artifactMIMEType?: string;
  append?: boolean;
  replace?: boolean;
};

export type ArtifactPullQuery = {
  name: string;
  retry?: number;
  retryDelay?: string;
  tlsVerify?: boolean;
};

export type ArtifactPushQuery = {
  retry?: number;
  retryDelay?: string;
  tlsVerify?: boolean;
};

export type ArtifactRemoveAllQuery = {
  artifacts?: Array<string>;
  all?: boolean;
  ignore?: boolean;
};

export type ContainerArchivePutQuery = {
  path: string;
  pause?: boolean;
};

export type ContainerArchiveQuery = {
  path: string;
  rename?: string;
};

export type ContainerAttachQuery = {
  detachKeys?: string;
  logs?: boolean;
  stream?: boolean;
  stdout?: boolean;
  stderr?: boolean;
  stdin?: boolean;
};

export type ContainerChangesQuery = {
  parent?: string;
  diffType?: "all" | "container" | "image";
};

export type ContainerCheckpointQuery = {
  keep?: boolean;
  leaveRunning?: boolean;
  tcpEstablished?: boolean;
  export?: boolean;
  ignoreRootFS?: boolean;
  ignoreVolumes?: boolean;
  preCheckpoint?: boolean;
  withPrevious?: boolean;
  fileLocks?: boolean;
  printStats?: boolean;
};

export type ContainerInspectQuery = {
  size?: boolean;
};

export type ContainerKillQuery = {
  signal?: string;
};

export type ContainerListQuery = {
  all?: boolean;
  limit?: number;
  last?: number;
  external?: boolean;
  namespace?: boolean;
  pod?: boolean;
  size?: boolean;
  sync?: boolean;
  filters?: string;
};

export type ContainerLogsQuery = {
  follow?: boolean;
  stdout?: boolean;
  stderr?: boolean;
  since?: string;
  until?: string;
  timestamps?: boolean;
  tail?: string;
};

export type ContainerMountQuery = {
  external?: boolean;
};

export type ContainerPruneQuery = {
  filters?: string;
};

export type ContainerRemoveQuery = {
  depend?: boolean;
  force?: boolean;
  ignore?: boolean;
  timeout?: number;
  v?: boolean;
};

export type ContainerRenameQuery = {
  name: string;
};

export type ContainerResizeQuery = {
  h?: number;
  w?: number;
  running?: boolean;
};

export type ContainerRestartQuery = {
  t?: number;
  timeout?: number;
};

export type ContainerRestoreQuery = {
  name?: string;
  keep?: boolean;
  tcpEstablished?: boolean;
  tcpClose?: boolean;
  import?: boolean;
  ignoreRootFS?: boolean;
  ignoreVolumes?: boolean;
  ignoreStaticIP?: boolean;
  ignoreStaticMAC?: boolean;
  fileLocks?: boolean;
  printStats?: boolean;
  pod?: string;
};

export type ContainerStartQuery = {
  detachKeys?: string;
};

export type ContainerStatsAllQuery = {
  containers?: Array<string>;
  stream?: boolean;
  interval?: number;
  all?: boolean;
};

export type ContainerStatsQuery = {
  stream?: boolean;
};

export type ContainerStopQuery = {
  timeout?: number;
  ignore?: boolean;
};

export type ContainerTopQuery = {
  stream?: boolean;
  delay?: number;
  ps_args?: Array<string>;
};

export type ContainerUpdateQuery = {
  restartPolicy?: string;
  restartRetries?: number;
};

export type ContainerWaitQuery = {
  condition?: Array<
    | "configured"
    | "created"
    | "exited"
    | "healthy"
    | "initialized"
    | "paused"
    | "removing"
    | "running"
    | "stopped"
    | "stopping"
    | "unhealthy"
  >;
  interval?: string;
};

export type ExecResizeQuery = {
  h?: number;
  w?: number;
  running?: boolean;
};

export type GenerateKubeQuery = {
  names: Array<string>;
  service?: boolean;
  type?: string;
  replicas?: number;
  noTrunc?: boolean;
  podmanOnly?: boolean;
};

export type GenerateSystemdQuery = {
  useName?: boolean;
  new?: boolean;
  noHeader?: boolean;
  startTimeout?: number;
  stopTimeout?: number;
  restartPolicy?:
    | "no"
    | "on-success"
    | "on-failure"
    | "on-abnormal"
    | "on-watchdog"
    | "on-abort"
    | "always";
  containerPrefix?: string;
  podPrefix?: string;
  separator?: string;
  restartSec?: number;
  wants?: Array<string>;
  after?: Array<string>;
  requires?: Array<string>;
  additionalEnvVariables?: Array<string>;
  templateUnitFile?: boolean;
};

export type ImageBuildQuery = {
  dockerfile?: string;
  t?: string;
  allplatforms?: boolean;
  additionalbuildcontexts?: Array<string>;
  extrahosts?: string;
  nohosts?: boolean;
  remote?: string;
  q?: boolean;
  compatvolumes?: boolean;
  createdannotation?: boolean;
  sourcedateepoch?: number;
  rewritetimestamp?: boolean;
  timestamp?: number;
  inheritlabels?: boolean;
  inheritannotations?: boolean;
  nocache?: boolean;
  cachefrom?: string;
  pull?: boolean;
  rm?: boolean;
  forcerm?: boolean;
  memory?: number;
  memswap?: number;
  cpushares?: number;
  cpusetcpus?: string;
  cpuperiod?: number;
  cpuquota?: number;
  buildargs?: string;
  shmsize?: number;
  squash?: boolean;
  labels?: string;
  layerLabel?: Array<string>;
  layers?: boolean;
  networkmode?: string;
  platform?: string;
  target?: string;
  outputs?: string;
  httpproxy?: boolean;
  unsetenv?: Array<string>;
  unsetlabel?: Array<string>;
  unsetannotation?: Array<string>;
  volume?: Array<string>;
  manifest?: string;
};

export type ImageChangesQuery = {
  parent?: string;
  diffType?: "all" | "container" | "image";
};

export type ImageCommitQuery = {
  container: string;
  author?: string;
  changes?: Array<string>;
  comment?: string;
  format?: string;
  pause?: boolean;
  squash?: boolean;
  repo?: string;
  stream?: boolean;
  tag?: string;
};

export type ImageExportQuery = {
  format?: string;
  references?: Array<string>;
  compress?: boolean;
  ociAcceptUncompressedLayers?: boolean;
};

export type ImageGetQuery = {
  format?: string;
  compress?: boolean;
};

export type ImageImportQuery = {
  changes?: Array<string>;
  message?: string;
  reference?: string;
  url?: string;
};

export type ImageListQuery = {
  all?: boolean;
  filters?: string;
};

export type ImagePruneQuery = {
  all?: boolean;
  external?: boolean;
  buildcache?: boolean;
  filters?: string;
};

export type ImagePullQuery = {
  reference?: string;
  quiet?: boolean;
  compatMode?: boolean;
  pullProgress?: boolean;
  Arch?: string;
  OS?: string;
  Variant?: string;
  policy?: string;
  tlsVerify?: boolean;
  allTags?: boolean;
};

export type ImagePushQuery = {
  destination?: string;
  forceCompressionFormat?: boolean;
  compressionFormat?: string;
  compressionLevel?: number;
  tlsVerify?: boolean;
  quiet?: boolean;
  format?: string;
  all?: boolean;
  removeSignatures?: boolean;
  retry?: number;
  retryDelay?: string;
};

export type ImageRemoveAllQuery = {
  images?: Array<string>;
  all?: boolean;
  force?: boolean;
  ignore?: boolean;
  lookupManifest?: boolean;
};

export type ImageRemoveQuery = {
  force?: boolean;
  ignore?: boolean;
  lookupManifest?: boolean;
};

export type ImageScpQuery = {
  destination?: string;
  quiet?: boolean;
};

export type ImageSearchQuery = {
  term?: string;
  limit?: number;
  filters?: string;
  tlsVerify?: boolean;
  listTags?: boolean;
};

export type ImageTagQuery = {
  repo?: string;
  tag?: string;
};

export type ImageTreeQuery = {
  whatrequires?: boolean;
};

export type ImageUntagQuery = {
  repo?: string;
  tag?: string;
};

export type KubeApplyQuery = {
  caCertFile?: string;
  kubeConfig?: string;
  namespace?: string;
  service?: boolean;
  file?: string;
};

export type LocalBuildQuery = {
  localcontextdir: string;
  dockerfile?: string;
  t?: string;
  allplatforms?: boolean;
  additionalbuildcontexts?: Array<string>;
  extrahosts?: string;
  nohosts?: boolean;
  remote?: string;
  q?: boolean;
  compatvolumes?: boolean;
  createdannotation?: boolean;
  sourcedateepoch?: number;
  rewritetimestamp?: boolean;
  timestamp?: number;
  inheritlabels?: boolean;
  inheritannotations?: boolean;
  nocache?: boolean;
  cachefrom?: string;
  pull?: boolean;
  rm?: boolean;
  forcerm?: boolean;
  memory?: number;
  memswap?: number;
  cpushares?: number;
  cpusetcpus?: string;
  cpuperiod?: number;
  cpuquota?: number;
  buildargs?: string;
  shmsize?: number;
  squash?: boolean;
  labels?: string;
  layerLabel?: Array<string>;
  layers?: boolean;
  networkmode?: string;
  platform?: string;
  target?: string;
  outputs?: string;
  httpproxy?: boolean;
  unsetenv?: Array<string>;
  unsetlabel?: Array<string>;
  unsetannotation?: Array<string>;
  volume?: Array<string>;
  manifest?: string;
};

export type LocalImagesQuery = {
  path: string;
};

export type ManifestCreateQuery = {
  images: string;
  all?: boolean;
  amend?: boolean;
};

export type ManifestInspectQuery = {
  tlsVerify?: boolean;
};

export type ManifestModifyQuery = {
  tlsVerify?: boolean;
};

export type ManifestPushQuery = {
  addCompression?: Array<string>;
  forceCompressionFormat?: boolean;
  all?: boolean;
  tlsVerify?: boolean;
  quiet?: boolean;
};

export type ManifestPushV3Query = {
  destination: string;
  all?: boolean;
};

export type ManifestRemoveQuery = {
  ignore?: boolean;
};

export type NetworkCreateQuery = {
  ignoreIfExists?: boolean;
};

export type NetworkListQuery = {
  filters?: string;
};

export type NetworkPruneQuery = {
  filters?: string;
};

export type NetworkRemoveQuery = {
  force?: boolean;
};

export type PlayKubeDownQuery = {
  force?: boolean;
};

export type PlayKubeQuery = {
  annotations?: string;
  logDriver?: string;
  logOptions?: Array<string>;
  network?: Array<string>;
  noHosts?: boolean;
  noTrunc?: boolean;
  publishPorts?: Array<string>;
  publishAllPorts?: boolean;
  replace?: boolean;
  serviceContainer?: boolean;
  start?: boolean;
  staticIPs?: Array<string>;
  staticMACs?: Array<string>;
  tlsVerify?: boolean;
  userns?: string;
  wait?: boolean;
  build?: boolean;
};

export type PodKillQuery = {
  signal?: string;
};

export type PodListQuery = {
  filters?: string;
};

export type PodRemoveQuery = {
  force?: boolean;
  timeout?: number;
};

export type PodStatsQuery = {
  all?: boolean;
  namesOrIDs?: Array<string>;
  stream?: boolean;
  delay?: number;
};

export type PodStopQuery = {
  t?: number;
};

export type PodTopQuery = {
  stream?: boolean;
  delay?: number;
  ps_args?: string;
};

export type QuadletInstallQuery = {
  replace?: boolean;
  "reload-systemd"?: boolean;
};

export type QuadletListQuery = {
  filters?: string;
};

export type QuadletRemoveAllQuery = {
  quadlets?: Array<string>;
  all?: boolean;
  force?: boolean;
  ignore?: boolean;
  "reload-systemd"?: boolean;
};

export type QuadletRemoveQuery = {
  force?: boolean;
  ignore?: boolean;
  "reload-systemd"?: boolean;
};

export type SecretCreateQuery = {
  name: string;
  driver?: string;
  driveropts?: string;
  labels?: string;
  replace?: boolean;
  ignore?: boolean;
};

export type SecretInspectQuery = {
  showsecret?: boolean;
};

export type SecretListQuery = {
  filters?: string;
};

export type SecretRemoveQuery = {
  all?: boolean;
};

export type SystemCheckQuery = {
  quick?: boolean;
  repair?: boolean;
  repair_lossy?: boolean;
  unreferenced_layer_max_age?: string;
};

export type SystemEventsQuery = {
  since?: string;
  until?: string;
  filters?: string;
  stream?: boolean;
};

export type SystemPruneQuery = {
  all?: boolean;
  volumes?: boolean;
  external?: boolean;
  build?: boolean;
  filters?: string;
};

export type VolumeListQuery = {
  filters?: string;
};

export type VolumePruneQuery = {
  filters?: string;
};

export type VolumeRemoveQuery = {
  force?: boolean;
  timeout?: number;
};
